const baseVendors={1:[
['OTC DAIHEN','S40000','MUST','Robotic welding systems and power sources.','Benchmark automated MIG welding and integration.',['Adaptive welding','Offline programming','Data capture']],
['FANUC America','S40006','MUST','Industrial robots, vision, welding and handling.','Flexible automation, bin picking and future AMR integration.',['AI vision','AMR interfaces','Low-volume flexibility']],
['Yaskawa Motoman','S40020','MUST','Welding and material-handling robots.','Arc welding, spot welding and coordinated handling.',['Mobile manipulation','Welding analytics','AMR partnerships']],
['Path Robotics','S40037','MUST','AI-focused robotic welding.','Reduce programming effort for lower-volume automation.',['Production deployment','Part limitations','Data requirements']],
['Abagy Robotic Systems','S40043','HIGH','Software-led flexible robotic welding.','High-mix, low-volume weldments.',['CAD-to-path','Fixture tolerance','Robot support']],
['JR Automation','S40062','HIGH','Custom automation integration.','Combine robots, vision, controls and material flow.',['Automotive examples','AMR integration','Support']],
['Standard Bots','S44000','HIGH','Simplified industrial robot platform.','Compare modern deployment with traditional robots.',['Programming','Safety','Local support']],
['Universal Robots','S44006','MUST','Collaborative robots and partner ecosystem.','Machine tending, inspection and light handling.',['Mobile base','Vision','Safety']],
['Vectis Automation','S44071','MUST','Cobot welding packages.','Flexible welding for lower-volume assemblies.',['Changeover','Fixturing','Monitoring']],
['Roboflow','S46024','MUST','Custom computer-vision platform.','Defect detection and part-presence pilots.',['Edge deployment','Training effort','False rejects']],
['Complement AI','S46042','HIGH','Manufacturing AI technology.','Screen practical engineering and production use cases.',['Real deployment','ROI','Cybersecurity']],
['ABI Engine','S46060','HIGH','Manufacturing business intelligence.','Prioritize actions from production and quality data.',['Data connectors','Alerts','Workflow']],
['Boston Dynamics','S46069','MUST','Advanced mobile robotics.','Future-tech discussion for inspection and mobile manipulation; humanoid exhibit not confirmed.',['Deployable now','Manufacturing pilots','Safety']],
['Maneva AI','S20051','HIGH','AI for manufacturing applications.','Troubleshooting and engineering productivity.',['Customer example','Governance','Pilot scope']],
['Daifuku Automotive America','S11050','MUST','Automotive material handling and logistics.','AMR/AGV options for WIP and line-side delivery.',['AMR portfolio','Traffic management','Brownfield use']]],2:[
['Harms & Wende North America','S15100','MUST','Resistance-welding controls and monitoring.','Improve spot and projection weld confidence.',['Quality metrics','MES link','Retrofits']],
['Welding Technology Corp.','S15101','HIGH','Automotive resistance-welding controls.','Compare controls and weld-data capabilities.',['Retrofits','Analytics','Support']],
['NKE Nugget Profiler','S17088','HIGH','Resistance-weld evaluation.','Validate weld quality against destructive testing.',['Production method','Cycle time','Correlation']],
['Lincoln Electric','S29000','MUST','Robotic welding and production technology.','Robotic MIG and weld-data systems.',['Cobot vs robot','Weld data','Applications']],
['Miller Electric / Hobart / Bernard / Tregaskiss','S29043','MUST','Power sources, guns and robotic components.','Process stability and torch uptime.',['Maintenance','Gun monitoring','Consumables']],
['Fronius USA','S29054','MUST','Advanced robotic welding process control.','Thin gauge, spatter control and traceability.',['CMT','Data logging','Gap tolerance']],
['Dengensha America','S37000','MUST','Automotive resistance-welding systems.','Projection and nut welding automation.',['Force/current','Nut presence','Electrodes']],
['T.J. Snow Company','S37036','MUST','Resistance welders, controls and service.','Projection-weld modernization and support.',['Retrofits','Force checks','Training']],
['Taylor-Winfield Technologies','S39004','MUST','Projection welding and automation.','Automated nut welding and monitoring.',['Collapse monitoring','Force control','Traceability']],
['Xiris Automation','S39021','MUST','Weld vision and inspection.','Automated profile and defect inspection.',['Defects','Speed','False calls']],
['Rockwell Automation','S39024','MUST','Controls and connected-factory software.','Connect automation, data, quality and AI.',['AI use cases','Edge','MES']],
['SERVO-ROBOT','S39031','MUST','Seam tracking and robot guidance.','Improve weld placement and adaptability.',['Accuracy','Calibration','Compatibility']],
['UnitX','S39046','MUST','AI-powered industrial inspection.','Surface defect and assembly verification.',['Training','False rejects','Automotive examples']],
['Hexagon','C1556','MUST','Metrology and digital manufacturing.','Fixture validation and automated inspection.',['Inline metrology','Digital twin','Integration']],
['Virtek Vision','C2523','HIGH','Laser projection and guided manufacturing.','Assembly guidance and placement verification.',['Examples','Accuracy','CAD link']],
['FARO / Creaform','C2527 / C2625','MUST','Portable 3D scanning and measurement.','Layout, fixture validation and reverse engineering.',['Scan-to-CAD','Accuracy','Automation']],
['KEYENCE','C4228','MUST','Vision, sensors and measurement.','Presence, dimensions, guidance and inline quality.',['Demo','Tolerance','Data export']],
['Beckhoff Automation','C4408','HIGH','PC controls, motion and networking.','Flexible controls and edge computing.',['AI edge','Safety','Brownfield']],
['InspecVision','C7244','HIGH','Optical dimensional inspection.','Fast profile checks for flat stamped parts.',['Part size','Accuracy','Cycle time']]]};
